### ISSUE TITLE
Strict line breaks are not honored, which skews the statistics

### ISSUE THREAD

**Issue by mlao-pdx** [mihakralj/obsidian-textanalysis#1]
I write using semantic line breaks, for which I turned on the Strict Line Breaks setting. See the bottom of this screenshot:

<img width="1062" alt="Screenshot 2023-12-19 at 18 53 59" src="https://github.com/mihakralj/obsidian-textanalysis/assets/21014310/3d92c171-9b2d-49f6-b7ca-872552feaa64">

When I do that, these are the stats I get on a test note:

<img width="1618" alt="Screenshot 2023-12-19 at 19 00 31" src="https://github.com/mihakralj/obsidian-textanalysis/assets/21014310/deac2b44-bd3c-4b98-804c-7fa8681238e2">

I was expecting three (3) sentences and two (2) paragraphs, not two (2) sentences and nine (9) paragraphs. The latter seems to be a non-empty line count? While the two sentences seem to be the one (1) sentence offset plus the single line sentence on line seven (7).

**Comment by mihakralj** [comment]
could you send me the .md file with the text that miscalculates?

M
________________________________
From: MLAO ***@***.***>
Sent: Tuesday, December 19, 2023 7:12 PM
To: mihakralj/obsidian-textanalysis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mihakralj/obsidian-textanalysis] Strict line breaks are not honored, which skews the statistics (Issue #1)


I write using semantic line breaks, for which I turned on the Strict Line Breaks setting. See the bottom of this screenshot:

Screenshot.2023-12-19.at.18.53.59.png (view on web)<https://github.com/mihakralj/obsidian-textanalysis/assets/21014310/3d92c171-9b2d-49f6-b7ca-872552feaa64>

When I do that, these are the stats I get on a test note:

Screenshot.2023-12-19.at.19.00.31.png (view on web)<https://github.com/mihakralj/obsidian-textanalysis/assets/21014310/deac2b44-bd3c-4b98-804c-7fa8681238e2>

I was expecting three (3) sentences and two (2) paragraphs, not two (2) sentences and nine (9) paragraphs. The latter seems to be a non-empty line count? While the two sentences seem to be the one (1) sentence offset plus the single line sentence on line seven (7).

**Comment by mlao-pdx** [comment]
> could you send me the .md file with the text that miscalculates? M

[Junk.md](https://github.com/mihakralj/obsidian-textanalysis/files/13722668/Junk.md)

Here you go.

**Comment by mihakralj** [comment]
I think I found a workable regex filter that can remove this issue; let me test some more before I release the pacth.

**Comment by mihakralj** [comment]
Fixed (I think). Please update the plugin to 1.1.0 and confirm.
