### ISSUE TITLE
Properties/Frontmatter included in document stats

### ISSUE THREAD

**Issue by hmbgnr** [mihakralj/obsidian-textanalysis#2]
When viewing stats for the entire document, any properties or frontmatter are included. This is most noticeable when documents are small. Included .txt file is the one from the screenshot.
![IMG_0151](https://github.com/mihakralj/obsidian-textanalysis/assets/1217630/a89ed75d-853a-4724-9b0c-b5fc901f8d1f)
[2023-12-30.txt](https://github.com/mihakralj/obsidian-textanalysis/files/13799021/2023-12-30.txt)

**Comment by mihakralj** [comment]
I tried several approaches how to filter out the 'non-text' text, but I either filter out too much or too little to make it universally applicable. for example, in the text that you attached, which words should count? should 'banner' count as a word? Or even a sentence and paragraph? Using a selection of text to point precisely what you want to measure is currently the best (most repeatable) approach.

```
banner_icon: "🗓️"
banner_y: 0.5
banner: https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNjAwOTd8MHwxfHNlYXJjaHwzfHxQbGFubmluZ3xlbnwwfDB8fHwxNzAzOTU2NjI0fDA&ixlib=rb-4.0.3&q=80&w=1080
---
Testing
```

**Comment by mihakralj** [comment]
Fixed (I think). Please update the plugin to 1.1.0 and confirm/
