### ISSUE TITLE
All values for metrics are 0

### ISSUE THREAD

**Issue by joshtownley** [mihakralj/obsidian-textanalysis#5]
When opening a file, all values read 0 (see screenshot). When I select a section of text, the values remain as 0 and nothing changes.
When reloading the app, or disabling and re-enabling the plugin, all toggle switches in the settings return to the 'off' position.

![Screenshot 2024-02-11 at 5 40 35 pm](https://github.com/mihakralj/obsidian-textanalysis/assets/95601566/d97e0e6f-9e85-41c3-9c89-5231fc859cf4)

**Comment by Eanredur** [comment]
Same issue here.
Reproduced it in a dummy vault. No other plugins, Text Analysis enabled, all scores remain zero.
Obsidian version 1.5.8 on Linux Mint (the most recent).

**Comment by Eanredur** [comment]
Update: In the version of the plugin that gets downloaded by Obsidian, a function is commented out. If you uncomment the "updateHeaderElementContent" block, it works. You also need to remove the string specification as that is from TypeScript, but the plugin gets downloaded as plain JavaScript. 

I have no idea why that is and maybe there is a good reason for it, but putting the function back it makes it work.

**Comment by Eanredur** [comment]
**Before starting, I have not read the code and I have not looked into developing Obsidian plugins. I have no idea what I am doing, and maybe it was commented out for a good reason. Be aware that modifying code that you do not understand can have grave consequences.**

If you still want to proceed:

You should find it in the main.js at
.
└── YourVaultFolder/
    ├── .obsidian/
    │   ├── plugins/
    │   │   ├── ... (one folder per plugin)
    │   │   └── textanalysis/
    │   │       └── main.js
    │   └── ... (other stuff depending on your vault)
    ├── ... (the vault content)
    ├── ...
    └── ...

The .obsidian folder may be hidden, depending on your file browser settings. <ctrl>+h should unhide it.
Open the main.js with a text editor of your choice (take one that can open long files)  and search for "updateHeaderElementContent"
Search for an instance that looks like this:
'
  // updateHeaderElementContent(title string) {
  //   const elements = document.querySelectorAll('.mod-right-split > .workspace-tabs:not(.mod-top) .workspace-tab-header-spacer');
  //   elements.forEach(element => {
  //     element.setAttribute('data-content', 'Text analysis - ' + title);
  //   });
  // }
`
Remove the leading // on every row OF THE BLOCK. 
Then remove the "string" from the parameters. 
I forgot how it was formatted commented out originally, maybe the block is commented out in /* */ syntax. In any case remove the enclosing symbols and remove the string specification.

It should work now.

**Comment by raphaelstevens** [comment]
Many thanks for your help. It works now.
